# runtime: python3
# api_version: 1
# threadsafe: true
#
#

runtime: python37

instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /src/static
  static_dir: static
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
#
# libraries:
#   - name: ssl
#     version: latest
